name: Deploy to GitHub Pages

on:
  push:
    branches:
      - gh-pages

permissions:
  contents: write  # ¡Esto es muy importante!

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Deploy a GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # Publicar desde la raíz

